version: '3.7'
services:
  create_react:
    container_name: create_react
    image: create_react:prod
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    ports: 
      - '80:80'
      - '443:443'