version: '3.7'
services:
  create_react:
    container_name: create_react
    image: create_react
    build:
      context: .  
      dockerfile: Dockerfile
    ports: 
      - '3000:3005'  
      - '443:443' 